<a href="https://colab.research.google.com/github/jaysuryavanshi378/Simple_Python_Programs/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Operations on Matrices without using NumPy in Python**

###1. Calculate the determinant of 3X3 matrix.

In [2]:
a=[[1,2,5],
   [2,7,3],
   [2,4,7]]
determinant = (a[0][0] *( (a[1][1] * a[2][2])-(a[2][1] * a[1][2]))
              -a[0][1] *( (a[1][0] * a[2][2])-(a[2][0] * a[1][2]))
              +a[0][2] *( (a[1][0] * a[2][1])-(a[2][0] * a[1][1])))
print(f"The determinant of the matrix is {determinant}")

The determinant of the matrix is -9


###2. Find the inverse of 3X3 matrix.

In [9]:
A = [[1, 2, 5],
     [2, 7, 3],
     [2, 4, 7]]

a,b,c = A[0]
d,e,f = A[1]
g,h,i = A[2]

det = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

if det == 0:
    print("Inverse does not exist")
else:
    inv = [
        [((e*i - f*h)/det), (c*h - b*i)/det, (b*f - c*e)/det],
        [(f*g - d*i)/det, (a*i - c*g)/det, (c*d - a*f)/det],
        [(d*h - e*g)/det, (b*g - a*h)/det, (a*e - b*d)/det]
    ]

    print("Inverse Matrix:")
    for row in inv:
        print([f"{x:.2f}" for x in row])


Inverse Matrix:
['-4.11', '-0.67', '3.22']
['0.89', '0.33', '-0.78']
['0.67', '-0.00', '-0.33']


### 3.Solve a system of linear equations using matrix methods.
Equations:-<br>
  2x + 3y = 11<br>
  4x - 1y = 5


In [10]:
a1, b1, c1 = 2, 3, 11
a2, b2, c2 = 4, -1, 5

# Main determinant
D = a1*b2 - a2*b1

if D == 0:
    print("No unique solution")
else:
    Dx = c1*b2 - c2*b1
    Dy = a1*c2 - a2*c1

    x = Dx / D
    y = Dy / D

    print("Solution:")
    print(f"x = {x:.2f}")
    print(f"y = {y:.2f}")


Solution:
x = 1.86
y = 2.43


##**Operations on Matrices with using NumPy in Python**

###1. Calculate the determinant of 3X3 matrix.

In [13]:
import numpy as np

A = np.array([[1,2,5],
              [2,7,3],
              [2,4,7]])

det = np.linalg.det(A)

print("The determinant of the matrix is ", np.round(det))


The determinant of the matrix is  -9.0


###2. Find the inverse of 3X3 matrix.

In [18]:
import numpy as np

A = np.array([[1, 2, 5],
              [2, 7, 3],
              [2, 4, 7]])

inv = np.linalg.inv(A)

print("Inverse Matrix:")
print(np.round(inv,2))


Inverse Matrix:
[[-4.11 -0.67  3.22]
 [ 0.89  0.33 -0.78]
 [ 0.67  0.   -0.33]]


### 3.Solve a system of linear equations using matrix methods.
Equations:-<br>
  2x + 3y = 11<br>
  4x - 1y = 5

In [20]:
import numpy as np

A = np.array([[2, 3],
              [4, -1]])

B = np.array([11, 5])

solution = np.linalg.solve(A, B)

x, y = solution

print("The values of x and y are :")
print(f"x = {x:.2f}")
print(f"y = {y:.2f}")


The values of x and y are :
x = 1.86
y = 2.43
